# Generated by Django 4.1 on 2022-11-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_mngstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MngValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
