# Generated by Django 4.1 on 2022-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_mngvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mngstatus',
            name='description',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado')], max_length=20),
        ),
    ]
