# Generated by Django 4.1 on 2022-11-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_mngstatus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MngFactElect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEmision', models.CharField(choices=[('1', 'Emisión normal')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
