# Generated by Django 4.1 on 2022-11-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_mngfactelect'),
    ]

    operations = [
        migrations.AddField(
            model_name='mngfactelect',
            name='tipoAmbiente',
            field=models.CharField(choices=[('1', 'Pruebas '), ('2', 'Producción')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='mngfactelect',
            name='tipoComprobante',
            field=models.CharField(choices=[('01', 'Factura'), ('03', 'LIQUIDACIÓN DE COMPRA DE BIENES Y PRESTACIÓN DE SERVICIOS'), ('04', 'NOTA DE CRÉDITO '), ('05', 'NOTA DE DÉBITO'), ('06', 'GUÍA DE REMISIÓN'), ('07', 'COMPROBANTE DE RETENCIÓN')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='mngdocumenttype',
            name='description',
            field=models.CharField(choices=[('05', 'CÉDULA'), ('04', 'RUC'), ('03', 'PASAPORTE'), ('07', 'VENTA A CONSUMIDOR FINAL'), ('08', 'IDENTIFICACIÓN DELEXTERIOR')], max_length=20),
        ),
    ]
