# Generated by Django 4.1 on 2022-11-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_mngdocumenttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mngfactelect',
            name='tipoAmbiente',
            field=models.CharField(choices=[('1', 'Pruebas '), ('2', 'Producción')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mngfactelect',
            name='tipoComprobante',
            field=models.CharField(choices=[('01', 'Factura'), ('03', 'LIQUIDACIÓN DE COMPRA DE BIENES Y PRESTACIÓN DE SERVICIOS'), ('04', 'NOTA DE CRÉDITO '), ('05', 'NOTA DE DÉBITO'), ('06', 'GUÍA DE REMISIÓN'), ('07', 'COMPROBANTE DE RETENCIÓN')], max_length=2),
        ),
    ]
