# Generated by Django 4.1 on 2022-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_mngfactelect_tipoambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mngdocumenttype',
            name='description',
            field=models.CharField(choices=[('05', 'CÉDULA'), ('04', 'RUC'), ('06', 'PASAPORTE'), ('07', 'VENTA A CONSUMIDOR FINAL'), ('08', 'IDENTIFICACIÓN DEL EXTERIOR')], max_length=20),
        ),
    ]
