# Generated by Django 4.1 on 2022-11-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_mngdocumenttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mngfactelect',
            name='codImp',
            field=models.CharField(choices=[('2', 'IVA '), ('3', 'ICE'), ('5', 'IRBPNR')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
