# Generated by Django 4.1 on 2022-12-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_mngfactelect_tarifiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='MngPaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('01', 'SIN UTILIZACION DEL SISTEMA FINANCIERO'), ('15', 'COMPENSACIÓN DE DEUDAS'), ('16', 'TARJETA DE DÉBITO'), ('17', 'DINERO ELECTRÓNICO'), ('18', 'TARJETA PREPAGO'), ('19', 'TARJETA DE CRÉDITO'), ('20', 'OTROS CON UTILIZACIÓN DEL SISTEMA FINANCIERO'), ('21', 'ENDOSO DE TÍTULOS')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
