# Generated by Django 4.1 on 2023-01-07 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0013_mngpaymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mngproductbrand',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_m_mngpb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mngproductbrand',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mngproductcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_m_mngpc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mngproductcategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
