# Generated by Django 4.1 on 2022-10-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_is_paid_invoice_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(null=True),
        ),
    ]
