# Generated by Django 4.1 on 2022-10-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_created_date_alter_invoice_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
