# Generated by Django 4.1 on 2022-10-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_mngstatus'),
        ('invoices', '0007_alter_invoice_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mngStatus_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.mngstatus'),
        ),
    ]
