# Generated by Django 4.1 on 2022-10-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_mngstatus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_customer_id',
        ),
    ]
