# Generated by Django 4.1 on 2022-10-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoice_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
