# Generated by Django 4.1 on 2022-10-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
