# Generated by Django 4.1 on 2022-10-23 21:50

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_no',
            field=models.IntegerField(default=invoices.models.invoice_number, unique=True),
        ),
    ]
