# Generated by Django 4.1 on 2022-10-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Invoice_no_final',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
