# Generated by Django 4.1 on 2022-10-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_document_number'),
        ('invoices', '0016_invoice_invoice_no_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to='customers.customer'),
        ),
    ]
