# Generated by Django 4.1 on 2022-12-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_mngpaymenttype'),
        ('invoices', '0017_alter_invoice_billing_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.mngpaymenttype'),
        ),
    ]
