# Generated by Django 4.1 on 2022-11-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nombCom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='numRuc',
            field=models.IntegerField(default=1803483716001, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='razSocial',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
