# Generated by Django 4.1 on 2022-11-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_nombcom_account_numruc_account_razsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='numRuc',
            field=models.IntegerField(unique=True),
        ),
    ]
