# Generated by Django 4.1 on 2022-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_numruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contribEspec',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='dirEstablec',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='dirMatr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='obligContab',
            field=models.BooleanField(default=False),
        ),
    ]
