# Generated by Django 4.1 on 2022-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_contribespec_account_direstablec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dirEstablec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='dirMatr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='nombCom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='numRuc',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='razSocial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
