# Generated by Django 4.1 on 2022-11-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_numruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contribEspec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
