# Generated by Django 4.1 on 2022-11-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_contribespec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='numRuc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
