# Generated by Django 4.1 on 2022-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_numruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contribEspec',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
