# Generated by Django 4.1 on 2023-01-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_contribespec'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
