# Generated by Django 4.1 on 2023-01-05 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_admin_id_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
