# Generated by Django 4.1 on 2022-10-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.IntegerField(unique=True),
        ),
    ]
