# Generated by Django 4.1 on 2022-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
