# Generated by Django 4.1 on 2022-09-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_mngproductbrand'),
        ('providers', '0001_initial'),
        ('products', '0003_variation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='boughtPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='discountPorcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mngProductBrand_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.mngproductbrand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mngProductCategory_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.mngproductcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/products')),
                ('default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
