# Generated by Django 4.1 on 2022-09-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_mngproductbrand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='boughtPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='discountPorcentage',
            field=models.IntegerField(),
        ),
    ]
