# Generated by Django 4.1 on 2022-09-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_boughtprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountPorcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
