# Generated by Django 4.1 on 2022-09-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
