# Generated by Django 4.1 on 2022-11-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_0_tax',
            field=models.BooleanField(default=False),
        ),
    ]
